services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  hotel-service:
    build:
      context: .
      dockerfile: hotel-service/Dockerfile
    container_name: hotel-service
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SECURITY_JWT_SECRET=CHANGE_ME_SUPER_SECRET_32+_CHARS_MINIMUM

  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    container_name: booking-service
    depends_on:
      - eureka-server
      - hotel-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SECURITY_JWT_SECRET=CHANGE_ME_SUPER_SECRET_32+_CHARS_MINIMUM
      - HOTEL_BASE_URL=http://hotel-service:8081

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - eureka-server
      - booking-service
      - hotel-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
